- .github/workflows/test.yml
- Makefile
- tests/config_test.go
Simple PR to officially support AMD64 builds.
- Remove hardcoded libx264.a path.
- Adds AMD64 to test  ci matrix.
- Small update to binary path for tests.
- Build/test working in local canon container ✅ 
- Test CI successful ✅
> [RSDK-8794] - Add AMD64 support

- cam/encoder.go
Moves from pixel by pixel fill to a row-wise copy to unpad yuv422 bytes.
prev: `2.23487ms`
new:  `622.487µs`
~3.5X faster
> [RSDK-8756] - Make YUV422 parser fast

- Makefile
- tests/config_test.go
- tests/fetch_test.go
- tests/save_test.go
- Moved from using `t.Fatal` to viam test package.
- Fixed segfault issue related to encoding with fake cam dependency.
- Added a cleanup utility to delete temporary storage files between viam-server runs.
- Added real-time async save test case.
- Added checks to to error message strings.
- Added checks to make sure that video clips are playable.
> I did not add in struct template loops as it did not make sense for config tests since template varies across tests.
> [RSDK-8848] - Test improvements bucket

- cam/cam.go
- cam/encoder.go
- examples/save_client.go
- go.mod
There was an issue where the segmenter would flake out after some time. This was due to a keyframe not being correctly inserted into the beginning of the segment as expected. It turns out, the `gop_size` encoder settings are more of a recommendation than an absolutely firm keyframe interval. Dependenging on scene changes, a keyframe could be inserted earlier than expected throwing off the synchronization between the encoder and segmenter.
FFmpeg codec options actually include a `force_key_frames` expression handler, so we do not even have to hand roll the key frame forces in our image loop! Basically a one line opt call to fix this : )
- Long running test with `viamrtsp` camera of size 960x480 and 20FPS
- ~5 hours, ~3000 segments 
- All playable so far... …
> [RSDK-8903] - Implement simple keyframe force interval

- cam/utils.go
Simple pr to remove erroneous files from file lookup and storage matcher for concats.
For example  `.DS_STORE` files on macos will now be ignored.
- manually tested with .DS_STORE file ✅ 
- added test video file with incorrect file name ✅
> [RSDK-8891] - Remove malformed filenames from concat operation

- cam/encoder.go
Despite having successful 24 hr runs on linux, I am still getting reports of flaky behavior on Darwin. This PR removes FFmpeg handling of keyframe forces entirely, and instead adds in manual keyframe forces in the encoder loop.
- Removes `gop_size` encoder setter entirely to avoid any conflicting behavior.
- Removes keyframe force expression.
- Adds manual keyframe flag every second.
- linux ✅ 
- 3 hour test, 500 segments ✅ 
- overnight test ✅
- darwin ✅ 
- 3 hour test, 500 segments ✅ 
- overnight test ✅
> Manually force keyframes in encoder loop

- README.md
- go.mod
- meta.json
> Depending on testing from PR #20 
- Makes module public
- Improvements to README
> [RSDK-8760] - README improvements

- tests/config_test.go
- tests/fetch_test.go
- tests/save_test.go
Replaced `t.Fatalf()` with `test.That()` to match the format of the rest of the tests
> RSDK-8853: Replace fatal with test.That in do_command tests

- .github/workflows/publish.yml
- cam/cam.go
- meta.json
There was an issue with using `uplaod-main` action in Darwin runners -- moving to build action to simplify things and get automated Darwin uploads to work.
Tested with a personal module upload on fork. See successful run [here](https://github.com/seanavery/video-store/actions/runs/12168824579/job/33940407748?pr=1).
> Use build action

- cam/cam.go
This PR simply adds a ticker throttle based on the specified framerate to the `fetchFrames` routine to prevent over-polling of the source camera. See ticket [here](https://viam.atlassian.net/browse/RSDK-9538) for analysis.
- Verify that fetchFrames is now throttled to framerate ✅ 
```
-16T16:39:17.463Z"}
2024-12-16T16:39:18.454Z        INFO    rdk:component:camera/video-store        cam/cam.go:376  Current FPS: 19.18      {"log_ts":"2024-12-16T16:39:18.451Z"}
2024-12-16T16:39:19.463Z        INFO    rdk:component:camera/video-store        cam/cam.go:376  Current FPS: 19.03      {"log_ts":"2024-12-16T16:39:19.461Z"}
2024-12-16T16:39:20.416Z        INFO    rdk:component:camera/video-store        cam/cam.go:376  Current FPS: 18.97      {"log_ts":"2024-12-16T16:39:20.411Z"} …
```
> [RSDK-9538] - Throttle frame fetches by configured framerate

- cam/cam.go
Return a single empty byte from Image to avoid Control frontend spitting up errors.
- Verify we no longer get error logs ✅ 
- Verify nothing breaks in the frontend ✅
> [RSDK-9553] - Avoid RenderFrame log spam

- README.md
- cam/cam.go
- tests/config_test.go
[RSDK-9573](https://viam.atlassian.net/browse/RSDK-9573)
[RSDK-9573]: https://viam.atlassian.net/browse/RSDK-9573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Tested with config:
```
{
"components": [
{
"name": "webcam-cam",
"namespace": "rdk",
"type": "camera",
"model": "webcam",
"attributes": {
"video_path": "FDF90FEB-59E5-4FCF-AABD-DA03C4E19BFB"
}
},
{
"name": "transform-cam",
"namespace": "rdk",
"type": "camera",
"model": "transform",
"attributes": {
"pipeline": [
{
"attributes": {
"y_max_px": 0.4,
"x_min_px": 0.3,
"y_min_px": 0.2,
"x_max_px": 0.6
},
"type": "crop"
},
{
"type": "rotate",
"attributes": {
"angle_degs": 270
}
}
],
"source": "webcam-cam"
}
},
{
"name": "rtsp-cam-1",
"namespace": "rdk",
"type": "camera",
"model": …
```
> [RSDK-9573]   Autodetect height and width of source cam in video store

- Makefile
- README.md
- cam/cam.go
- cam/encoder.go
- cam/segmenter.go
- tests/config_test.go
- tests/fetch_test.go
- tests/save_test.go
This addresses crashes in the encoder downstream from mismatches between the actual frames received from the source camera and the encoder/segmenter parameters. We now defer initialization of the encoder and segmenter until we receive a frame and can reinitialize when the dimensions change. If the Image endpoint of the source camera changes we will spin off a new initialization flow to handle the new size.
Beforehand you can reliably repro a crash with wildly off `cam_props`. For instance, the following parameters with a 640x480 source camera.
```
"cam_props": {
"height": 10,
"framerate": 20,
"width": 10000
}
```
Will show the following segfault trace:
```
\_ Assertion ((src_linesize) >= 0 ? (src_linesize) : (-(src_linesize))) >= bytewidth failed at libavutil/imgutils.c:350 …
```
> [RSDK-9653, RSDK-9673] - Make resilient to unknown and changing frame sizes

- Makefile
- README.md
- cam/cam.go
- cam/encoder.go
- cam/mime.go
- cam/mime_test.go
This PR adds YUYV mime type handling for more efficient frame fetching from viamrtsp.
- Adds an optionsl attribute `yuyv` to flag we want to fetch raw YUYV frames.
- Switches to caching AVFrame instead of go bytes for use in the processFrames routine.
- Adds YUYV conversion setup and handler.
- Switches to using LibAV MJPEG decoder instead of using the go jpeg decoder.
- automated tests:
- Add unit test for mjpeg decoder ✅ 
- Add unit test for yuyv to yuv420p converter ✅ 
- Add unit test for YUYV magic header unpacker ✅ 
- manual tests:
- yuyv segments playable ✅ 
- mjpeg segments playable ✅ 
- yuyv live size change handling ✅ 
- jpeg live size change handling ✅
> [RSDK-9701] - Add YUYV mimetype handling

- README.md
- cam/cam.go
- tests/config_test.go
Simple PR to allow the module to handle do-command requests even if camera is not available.
- No longer failing to initialize module with missing camera.
- Preventing processing of frames when camera is missing.
- automated tests:
- config test succeeds with no camera attr ✅ 
- implicit camera dep check ✅ 
- manual tests 
- base case with camera dep:
- module initializes ✅ 
- video saves ✅
- source camera does not exist:
- module initiializes ✅ 
- no video saved ✅ 
- save do-command works ✅ 
- fetch do-command works ✅ 
- reconfigures:
- no camera -> adding camera
- initialization ✅
- video storage ✅ 
- save ✅ 
- fetch ✅ 
- camera in config -> no camera in config
- initialization ✅ 
- video stops being stored ✅ 
- save ✅ 
- fetch ✅
> [RSDK-9790] - Allow video store to build without a camera dependency

- Makefile
- cmd/concat/cmd.go
- cmd/raw-segmenter-c/main.c
- go.mod
- model/camera/camera.go
- videostore/concat.c
- videostore/config.go
- videostore/rawsegmenter.c
- videostore/rawsegmenter.go
- videostore/rawsegmenter.h
- videostore/videostore.go
1. Add support for saving h265 video via the rawpacketizer including tags for QuickTime compatibility.
2. Change the signature of rawpacketizer to allow the caller to provide dts and not require extradata to be provided prior to writing the first packet.
3. Fix bug where if 2 whole segement files were concatenated the dts would repeat causing concatenation to fail.
> Add h265 embeded video store support

- cmd/module/cmd.go
- videostore/utils.c
- videostore/utils.go
- videostore/utils.h
See [ticket](https://viam.atlassian.net/browse/RSDK-10116) for description of problem flushing av logs in our C code. This PR just wraps the default logger from FFmpeg with a `fflush` to `stderr`.
Manual testing with `test_av_log` helper that logs now show up.
```
2025-03-06T18:18:39.105Z	ERROR	rdk.modmanager.viam_video-store.viam_video-store.StdErr	pexec/managed_process.go:292	
\_ This is an error message
2025-03-06T18:18:39.106Z	ERROR	rdk.modmanager.viam_video-store.viam_video-store.StdErr	pexec/managed_process.go:292	
\_ This is an info message
2025-03-06T18:18:39.106Z	ERROR	rdk.modmanager.viam_video-store.viam_video-store.StdErr	pexec/managed_process.go:292	
\_ This is a debug message
```
> [RSDK-10116] - Wrap default log callback with flush

- videostore/videostore.go
See [ticket](https://viam.atlassian.net/browse/CONSULT-764) for log details of occassional segfault in the encoder. This problem is due to a race condition where the mime handler attempts to operate on the `latestFrame` concurrently with the encoder. 
To fix this, we simply add locking around mime and encoder handling of the latestFrame.
- Manually tested that frame path video-store is working well with h264 and h265 rtsp cameras ✅ 
- Did not segfault over an overnight 12 hour run ✅ 
- Did not segfault when changing size of source camera 10 times ✅ 
- Segments are still playable and do not seem to be skipping significantly more frames with lock introduced ✅ 
https://github.com/user-attachments/assets/e21557c4-4113-4fd0-92b4-48d2820131de
Having a hard time setting up a reliable way to make …
> [CONSULT-764] - Fix race condition between mime handler and encoder

- go.mod
- go.sum
- videostore/config.go
- videostore/rawsegmenter.go
- videostore/segmenter.go
- videostore/videostore.go
[Ticket](https://viam.atlassian.net/browse/RSDK-10002)
1. Change rawsegementer to support closing and initializing multiple times.
2. Document the rawsegementer state machine
3. Make *RawSegmenter and it's methods public so they can be used by viamrtsp
4. Upgrade github.com/bluenviron/mediacommon from[ v1.9.2 to v1.13.3](https://github.com/bluenviron/mediacommon/compare/v1.9.2...v1.13.3) to make it the same as viamrtsp
5. unify `config.SourceTypeH264RTPPacket` and `config.SourceTypeH265RTPPacket`  into `config.SourceTypeRTP`
6. Create `config.SourceTypeReadOnly` so that viamrtsp hosted video-store can support `DoCommand(fetch) and DoCommand(save)` even when there is no camera configured.
7. move `cleanupStorage` into videostore.go rather than being duplicated on the 2 segmenters.
8. …
> [RSDK-10002] - make video store viamrtsp model

- tests/fetch_test.go
- videostore/concat.c
- videostore/videostore.go
Simply deleting file in fetch after it is read into go bytes.
If we comment out file removal from fetch flow, the success fetch test case will fail with a leftover file.
> [RSDK-10224] - Delete concated file during fetch

- tests/save_test.go
- videostore/videostore.go
[RSDK-10223](https://viam.atlassian.net/browse/RSDK-10223)
[RSDK-10223]: https://viam.atlassian.net/browse/RSDK-10223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Before PR (off registry)
After PR (local build off feature branch)
> [RSDK-10223] -   Return an error if async save command's `to` field is in the future

- README.md
- tests/fetch_test.go
- tests/save_test.go
- videostore/utils.go
- videostore/videostore.go
[RSDK-10486](https://viam.atlassian.net/browse/RSDK-10486)
[RSDK-10486]: https://viam.atlassian.net/browse/RSDK-10486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
```
{
"command": "save",
"from": "2025-04-18_14-32-02",
"to": "2025-04-18_14-32-12",
"metadata": "metadata",
"async": false
}
```
vs.
```
{
"command": "save",
"from": "2025-04-18_18-32-03Z",
"to": "2025-04-18_18-32-12Z",
"metadata": "metadata",
"async": false
}
```
Nice! Succeeded. Here are comparison videos from the two cmds
https://github.com/user-attachments/assets/6b74eb9f-9e6b-450c-8c6a-a960ba042c8a
https://github.com/user-attachments/assets/d5099227-0730-4a43-a891-0b64a4503b1b
`go run ./examples/fetch/fetch_client.go vs-1 2025-04-18_18-32-03Z 2025-04-18_18-32-12Z`
Fetch also …
> [RSDK-10486]   Support querying videos in UTC time

- README.md
Ran `viam module update`, verified that this works, then re-published the current docs until this PR is approved. There's a significant amount of documentation on DoCommand, so it might make sense to increase the visibility.
> Make DoCommand docs visible in the Viam app by nesting them within the referenced markdownlink section for inline docs
